# Generated by Django 4.2.4 on 2023-09-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_currentcase_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='working_hours',
            field=models.ManyToManyField(blank=True, to='accounts.timeslot'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot',
            field=models.CharField(choices=[('8-10', '8:00 AM - 10:00 AM'), ('10-12', '10:00 AM - 12:00 PM'), ('1-3', '1:00 PM - 3:00 PM'), ('3-5', '3:00 PM - 5:00 PM')], default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
