# Generated by Django 4.2.4 on 2023-09-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_timeslot_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='slot',
        ),
    ]
