# Generated by Django 4.2.4 on 2023-09-16 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_remove_timeslot_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='slot',
            field=models.CharField(choices=[('8-10', '8:00 AM - 10:00 AM'), ('10-12', '10:00 AM - 12:00 PM'), ('1-3', '1:00 PM - 3:00 PM'), ('3-5', '3:00 PM - 5:00 PM')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='working_hours',
            field=models.ManyToManyField(blank=True, default='09:00', to='accounts.timeslot'),
        ),
    ]
