# Generated by Django 4.2.4 on 2023-09-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_timeslot_slot_alter_lawyerprofile_working_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'slot')},
        ),
    ]
