# Generated by Django 4.2.4 on 2023-09-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_timeslot_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'slot')},
        ),
    ]
