# Generated by Django 4.2.4 on 2023-09-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_alter_timeslot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
