# Generated by Django 4.2.4 on 2023-09-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_booking_num_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='num_bookings',
        ),
    ]
